server:
  port: 8080
  #servlet:
    #context-path: /api
jwt:
  secret: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  lifetime: 5m

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    org.postgresql.Driver
#    com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/otziv
#    jdbc:postgresql://localhost:5432/otziv
#    jdbc:mysql://localhost:3308/otziv_o
    username: hunt
    password: 545321
  flyway:
    baseline-on-migrate: true

#logging:
 # level:
  #  org.springframework.security: trace

#  thymeleaf:
##    prefix: D:\Java\otziv\src\main\resources\templates
#    resources:
#        static-locations: D:\Java\otziv\src\main\resources\static\
#    cache-period: 0
#  cache: false