
server:
  port: 8080
jwt:
  secret: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  lifetime: 5m

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Настройки мультипарт загрузки


#    база данных на рег ру
#    url: jdbc:mysql://37.140.192.105:3306/u1215824_otziv?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: u1215824
#    password: Rkfql54532111

#    база данных на в игру ру
#    url: jdbc:mysql://46.254.20.38:3306/p478535_otziv?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: p478535_hunt
#    password: Rkfql54532111

#    локальная база данных
#    url: jdbc:mysql://localhost:3306/otziv
#    username: hunt
#    password: 545321

  #    Docker база данных
    url: jdbc:mysql://mysql:3306/otziv
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  flyway:
    baseline-on-migrate: true

#    username: hunt
#    password: 545321

#logging:
 # level:
  #  org.springframework.security: trace

#  thymeleaf:
##    prefix: D:\Java\otziv\src\main\resources\templates
#    resources:
#        static-locations: D:\Java\otziv\src\main\resources\static\
#    cache-period: 0
#  cache: false